"""Replace name with firstname and lastname

Revision ID: 0ce41bf9a96c
Revises: 304da6163f58
Create Date: 2024-10-16 23:03:01.321490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce41bf9a96c'
down_revision = '304da6163f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.Text(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
