"""Add attributes to User model


Revision ID: 304da6163f58
Revises: fccc43b2075a
Create Date: 2024-10-16 22:57:36.329320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304da6163f58'
down_revision = 'fccc43b2075a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_function', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.create_unique_constraint(None, ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('job_title')
        batch_op.drop_column('job_function')

    # ### end Alembic commands ###
